// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package invoice

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_Invoice                protoreflect.MessageDescriptor
	fd_Invoice_creator        protoreflect.FieldDescriptor
	fd_Invoice_index          protoreflect.FieldDescriptor
	fd_Invoice_Invoice_Number protoreflect.FieldDescriptor
	fd_Invoice_Customer_Name  protoreflect.FieldDescriptor
	fd_Invoice_Invoice_Date   protoreflect.FieldDescriptor
	fd_Invoice_Total_Amount   protoreflect.FieldDescriptor
	fd_Invoice_Due_Date       protoreflect.FieldDescriptor
)

func init() {
	file_invoice_invoice_invoice_proto_init()
	md_Invoice = File_invoice_invoice_invoice_proto.Messages().ByName("Invoice")
	fd_Invoice_creator = md_Invoice.Fields().ByName("creator")
	fd_Invoice_index = md_Invoice.Fields().ByName("index")
	fd_Invoice_Invoice_Number = md_Invoice.Fields().ByName("Invoice_Number")
	fd_Invoice_Customer_Name = md_Invoice.Fields().ByName("Customer_Name")
	fd_Invoice_Invoice_Date = md_Invoice.Fields().ByName("Invoice_Date")
	fd_Invoice_Total_Amount = md_Invoice.Fields().ByName("Total_Amount")
	fd_Invoice_Due_Date = md_Invoice.Fields().ByName("Due_Date")
}

var _ protoreflect.Message = (*fastReflection_Invoice)(nil)

type fastReflection_Invoice Invoice

func (x *Invoice) ProtoReflect() protoreflect.Message {
	return (*fastReflection_Invoice)(x)
}

func (x *Invoice) slowProtoReflect() protoreflect.Message {
	mi := &file_invoice_invoice_invoice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_Invoice_messageType fastReflection_Invoice_messageType
var _ protoreflect.MessageType = fastReflection_Invoice_messageType{}

type fastReflection_Invoice_messageType struct{}

func (x fastReflection_Invoice_messageType) Zero() protoreflect.Message {
	return (*fastReflection_Invoice)(nil)
}
func (x fastReflection_Invoice_messageType) New() protoreflect.Message {
	return new(fastReflection_Invoice)
}
func (x fastReflection_Invoice_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_Invoice
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_Invoice) Descriptor() protoreflect.MessageDescriptor {
	return md_Invoice
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_Invoice) Type() protoreflect.MessageType {
	return _fastReflection_Invoice_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_Invoice) New() protoreflect.Message {
	return new(fastReflection_Invoice)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_Invoice) Interface() protoreflect.ProtoMessage {
	return (*Invoice)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_Invoice) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Creator != "" {
		value := protoreflect.ValueOfString(x.Creator)
		if !f(fd_Invoice_creator, value) {
			return
		}
	}
	if x.Index != "" {
		value := protoreflect.ValueOfString(x.Index)
		if !f(fd_Invoice_index, value) {
			return
		}
	}
	if x.Invoice_Number != "" {
		value := protoreflect.ValueOfString(x.Invoice_Number)
		if !f(fd_Invoice_Invoice_Number, value) {
			return
		}
	}
	if x.Customer_Name != "" {
		value := protoreflect.ValueOfString(x.Customer_Name)
		if !f(fd_Invoice_Customer_Name, value) {
			return
		}
	}
	if x.Invoice_Date != "" {
		value := protoreflect.ValueOfString(x.Invoice_Date)
		if !f(fd_Invoice_Invoice_Date, value) {
			return
		}
	}
	if x.Total_Amount != "" {
		value := protoreflect.ValueOfString(x.Total_Amount)
		if !f(fd_Invoice_Total_Amount, value) {
			return
		}
	}
	if x.Due_Date != "" {
		value := protoreflect.ValueOfString(x.Due_Date)
		if !f(fd_Invoice_Due_Date, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_Invoice) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "invoice.invoice.Invoice.creator":
		return x.Creator != ""
	case "invoice.invoice.Invoice.index":
		return x.Index != ""
	case "invoice.invoice.Invoice.Invoice_Number":
		return x.Invoice_Number != ""
	case "invoice.invoice.Invoice.Customer_Name":
		return x.Customer_Name != ""
	case "invoice.invoice.Invoice.Invoice_Date":
		return x.Invoice_Date != ""
	case "invoice.invoice.Invoice.Total_Amount":
		return x.Total_Amount != ""
	case "invoice.invoice.Invoice.Due_Date":
		return x.Due_Date != ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: invoice.invoice.Invoice"))
		}
		panic(fmt.Errorf("message invoice.invoice.Invoice does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Invoice) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "invoice.invoice.Invoice.creator":
		x.Creator = ""
	case "invoice.invoice.Invoice.index":
		x.Index = ""
	case "invoice.invoice.Invoice.Invoice_Number":
		x.Invoice_Number = ""
	case "invoice.invoice.Invoice.Customer_Name":
		x.Customer_Name = ""
	case "invoice.invoice.Invoice.Invoice_Date":
		x.Invoice_Date = ""
	case "invoice.invoice.Invoice.Total_Amount":
		x.Total_Amount = ""
	case "invoice.invoice.Invoice.Due_Date":
		x.Due_Date = ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: invoice.invoice.Invoice"))
		}
		panic(fmt.Errorf("message invoice.invoice.Invoice does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_Invoice) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "invoice.invoice.Invoice.creator":
		value := x.Creator
		return protoreflect.ValueOfString(value)
	case "invoice.invoice.Invoice.index":
		value := x.Index
		return protoreflect.ValueOfString(value)
	case "invoice.invoice.Invoice.Invoice_Number":
		value := x.Invoice_Number
		return protoreflect.ValueOfString(value)
	case "invoice.invoice.Invoice.Customer_Name":
		value := x.Customer_Name
		return protoreflect.ValueOfString(value)
	case "invoice.invoice.Invoice.Invoice_Date":
		value := x.Invoice_Date
		return protoreflect.ValueOfString(value)
	case "invoice.invoice.Invoice.Total_Amount":
		value := x.Total_Amount
		return protoreflect.ValueOfString(value)
	case "invoice.invoice.Invoice.Due_Date":
		value := x.Due_Date
		return protoreflect.ValueOfString(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: invoice.invoice.Invoice"))
		}
		panic(fmt.Errorf("message invoice.invoice.Invoice does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Invoice) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "invoice.invoice.Invoice.creator":
		x.Creator = value.Interface().(string)
	case "invoice.invoice.Invoice.index":
		x.Index = value.Interface().(string)
	case "invoice.invoice.Invoice.Invoice_Number":
		x.Invoice_Number = value.Interface().(string)
	case "invoice.invoice.Invoice.Customer_Name":
		x.Customer_Name = value.Interface().(string)
	case "invoice.invoice.Invoice.Invoice_Date":
		x.Invoice_Date = value.Interface().(string)
	case "invoice.invoice.Invoice.Total_Amount":
		x.Total_Amount = value.Interface().(string)
	case "invoice.invoice.Invoice.Due_Date":
		x.Due_Date = value.Interface().(string)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: invoice.invoice.Invoice"))
		}
		panic(fmt.Errorf("message invoice.invoice.Invoice does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Invoice) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "invoice.invoice.Invoice.creator":
		panic(fmt.Errorf("field creator of message invoice.invoice.Invoice is not mutable"))
	case "invoice.invoice.Invoice.index":
		panic(fmt.Errorf("field index of message invoice.invoice.Invoice is not mutable"))
	case "invoice.invoice.Invoice.Invoice_Number":
		panic(fmt.Errorf("field Invoice_Number of message invoice.invoice.Invoice is not mutable"))
	case "invoice.invoice.Invoice.Customer_Name":
		panic(fmt.Errorf("field Customer_Name of message invoice.invoice.Invoice is not mutable"))
	case "invoice.invoice.Invoice.Invoice_Date":
		panic(fmt.Errorf("field Invoice_Date of message invoice.invoice.Invoice is not mutable"))
	case "invoice.invoice.Invoice.Total_Amount":
		panic(fmt.Errorf("field Total_Amount of message invoice.invoice.Invoice is not mutable"))
	case "invoice.invoice.Invoice.Due_Date":
		panic(fmt.Errorf("field Due_Date of message invoice.invoice.Invoice is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: invoice.invoice.Invoice"))
		}
		panic(fmt.Errorf("message invoice.invoice.Invoice does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_Invoice) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "invoice.invoice.Invoice.creator":
		return protoreflect.ValueOfString("")
	case "invoice.invoice.Invoice.index":
		return protoreflect.ValueOfString("")
	case "invoice.invoice.Invoice.Invoice_Number":
		return protoreflect.ValueOfString("")
	case "invoice.invoice.Invoice.Customer_Name":
		return protoreflect.ValueOfString("")
	case "invoice.invoice.Invoice.Invoice_Date":
		return protoreflect.ValueOfString("")
	case "invoice.invoice.Invoice.Total_Amount":
		return protoreflect.ValueOfString("")
	case "invoice.invoice.Invoice.Due_Date":
		return protoreflect.ValueOfString("")
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: invoice.invoice.Invoice"))
		}
		panic(fmt.Errorf("message invoice.invoice.Invoice does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_Invoice) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in invoice.invoice.Invoice", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_Invoice) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Invoice) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_Invoice) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_Invoice) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*Invoice)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.Creator)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Index)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Invoice_Number)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Customer_Name)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Invoice_Date)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Total_Amount)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Due_Date)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*Invoice)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.Due_Date) > 0 {
			i -= len(x.Due_Date)
			copy(dAtA[i:], x.Due_Date)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Due_Date)))
			i--
			dAtA[i] = 0x3a
		}
		if len(x.Total_Amount) > 0 {
			i -= len(x.Total_Amount)
			copy(dAtA[i:], x.Total_Amount)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Total_Amount)))
			i--
			dAtA[i] = 0x32
		}
		if len(x.Invoice_Date) > 0 {
			i -= len(x.Invoice_Date)
			copy(dAtA[i:], x.Invoice_Date)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Invoice_Date)))
			i--
			dAtA[i] = 0x2a
		}
		if len(x.Customer_Name) > 0 {
			i -= len(x.Customer_Name)
			copy(dAtA[i:], x.Customer_Name)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Customer_Name)))
			i--
			dAtA[i] = 0x22
		}
		if len(x.Invoice_Number) > 0 {
			i -= len(x.Invoice_Number)
			copy(dAtA[i:], x.Invoice_Number)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Invoice_Number)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.Index) > 0 {
			i -= len(x.Index)
			copy(dAtA[i:], x.Index)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Index)))
			i--
			dAtA[i] = 0x12
		}
		if len(x.Creator) > 0 {
			i -= len(x.Creator)
			copy(dAtA[i:], x.Creator)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Creator)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*Invoice)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Invoice: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Invoice: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Creator = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Index = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Invoice_Number", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Invoice_Number = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Customer_Name", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Customer_Name = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 5:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Invoice_Date", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Invoice_Date = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 6:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Total_Amount", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Total_Amount = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 7:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Due_Date", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Due_Date = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: invoice/invoice/invoice.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Invoice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Creator        string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Index          string `protobuf:"bytes,2,opt,name=index,proto3" json:"index,omitempty"`
	Invoice_Number string `protobuf:"bytes,3,opt,name=Invoice_Number,json=InvoiceNumber,proto3" json:"Invoice_Number,omitempty"`
	Customer_Name  string `protobuf:"bytes,4,opt,name=Customer_Name,json=CustomerName,proto3" json:"Customer_Name,omitempty"`
	Invoice_Date   string `protobuf:"bytes,5,opt,name=Invoice_Date,json=InvoiceDate,proto3" json:"Invoice_Date,omitempty"`
	Total_Amount   string `protobuf:"bytes,6,opt,name=Total_Amount,json=TotalAmount,proto3" json:"Total_Amount,omitempty"`
	Due_Date       string `protobuf:"bytes,7,opt,name=Due_Date,json=DueDate,proto3" json:"Due_Date,omitempty"`
}

func (x *Invoice) Reset() {
	*x = Invoice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_invoice_invoice_invoice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Invoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invoice) ProtoMessage() {}

// Deprecated: Use Invoice.ProtoReflect.Descriptor instead.
func (*Invoice) Descriptor() ([]byte, []int) {
	return file_invoice_invoice_invoice_proto_rawDescGZIP(), []int{0}
}

func (x *Invoice) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *Invoice) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

func (x *Invoice) GetInvoice_Number() string {
	if x != nil {
		return x.Invoice_Number
	}
	return ""
}

func (x *Invoice) GetCustomer_Name() string {
	if x != nil {
		return x.Customer_Name
	}
	return ""
}

func (x *Invoice) GetInvoice_Date() string {
	if x != nil {
		return x.Invoice_Date
	}
	return ""
}

func (x *Invoice) GetTotal_Amount() string {
	if x != nil {
		return x.Total_Amount
	}
	return ""
}

func (x *Invoice) GetDue_Date() string {
	if x != nil {
		return x.Due_Date
	}
	return ""
}

var File_invoice_invoice_invoice_proto protoreflect.FileDescriptor

var file_invoice_invoice_invoice_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x69, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x2f, 0x69, 0x6e, 0x76, 0x6f, 0x69, 0x63,
	0x65, 0x2f, 0x69, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0f, 0x69, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x2e, 0x69, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65,
	0x22, 0xe6, 0x01, 0x0a, 0x07, 0x49, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x25, 0x0a, 0x0e,
	0x49, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x5f, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x49, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x0d, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x43, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x49, 0x6e, 0x76, 0x6f,
	0x69, 0x63, 0x65, 0x5f, 0x44, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x49, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x44, 0x61, 0x74, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x54,
	0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x19,
	0x0a, 0x08, 0x44, 0x75, 0x65, 0x5f, 0x44, 0x61, 0x74, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x44, 0x75, 0x65, 0x44, 0x61, 0x74, 0x65, 0x42, 0xa2, 0x01, 0x0a, 0x13, 0x63, 0x6f,
	0x6d, 0x2e, 0x69, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x2e, 0x69, 0x6e, 0x76, 0x6f, 0x69, 0x63,
	0x65, 0x42, 0x0c, 0x49, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50,
	0x01, 0x5a, 0x20, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x73, 0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x69, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x2f, 0x69, 0x6e, 0x76, 0x6f,
	0x69, 0x63, 0x65, 0xa2, 0x02, 0x03, 0x49, 0x49, 0x58, 0xaa, 0x02, 0x0f, 0x49, 0x6e, 0x76, 0x6f,
	0x69, 0x63, 0x65, 0x2e, 0x49, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0xca, 0x02, 0x0f, 0x49, 0x6e,
	0x76, 0x6f, 0x69, 0x63, 0x65, 0x5c, 0x49, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0xe2, 0x02, 0x1b,
	0x49, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x5c, 0x49, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x5c,
	0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x10, 0x49, 0x6e,
	0x76, 0x6f, 0x69, 0x63, 0x65, 0x3a, 0x3a, 0x49, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_invoice_invoice_invoice_proto_rawDescOnce sync.Once
	file_invoice_invoice_invoice_proto_rawDescData = file_invoice_invoice_invoice_proto_rawDesc
)

func file_invoice_invoice_invoice_proto_rawDescGZIP() []byte {
	file_invoice_invoice_invoice_proto_rawDescOnce.Do(func() {
		file_invoice_invoice_invoice_proto_rawDescData = protoimpl.X.CompressGZIP(file_invoice_invoice_invoice_proto_rawDescData)
	})
	return file_invoice_invoice_invoice_proto_rawDescData
}

var file_invoice_invoice_invoice_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_invoice_invoice_invoice_proto_goTypes = []interface{}{
	(*Invoice)(nil), // 0: invoice.invoice.Invoice
}
var file_invoice_invoice_invoice_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_invoice_invoice_invoice_proto_init() }
func file_invoice_invoice_invoice_proto_init() {
	if File_invoice_invoice_invoice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_invoice_invoice_invoice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Invoice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_invoice_invoice_invoice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_invoice_invoice_invoice_proto_goTypes,
		DependencyIndexes: file_invoice_invoice_invoice_proto_depIdxs,
		MessageInfos:      file_invoice_invoice_invoice_proto_msgTypes,
	}.Build()
	File_invoice_invoice_invoice_proto = out.File
	file_invoice_invoice_invoice_proto_rawDesc = nil
	file_invoice_invoice_invoice_proto_goTypes = nil
	file_invoice_invoice_invoice_proto_depIdxs = nil
}
