// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: invoice/invoice/tx.proto

package invoice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Msg_UpdateParams_FullMethodName  = "/invoice.invoice.Msg/UpdateParams"
	Msg_Storeinvoice_FullMethodName  = "/invoice.invoice.Msg/Storeinvoice"
	Msg_CreateInvoice_FullMethodName = "/invoice.invoice.Msg/CreateInvoice"
	Msg_UpdateInvoice_FullMethodName = "/invoice.invoice.Msg/UpdateInvoice"
	Msg_DeleteInvoice_FullMethodName = "/invoice.invoice.Msg/DeleteInvoice"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	Storeinvoice(ctx context.Context, in *MsgStoreinvoice, opts ...grpc.CallOption) (*MsgStoreinvoiceResponse, error)
	CreateInvoice(ctx context.Context, in *MsgCreateInvoice, opts ...grpc.CallOption) (*MsgCreateInvoiceResponse, error)
	UpdateInvoice(ctx context.Context, in *MsgUpdateInvoice, opts ...grpc.CallOption) (*MsgUpdateInvoiceResponse, error)
	DeleteInvoice(ctx context.Context, in *MsgDeleteInvoice, opts ...grpc.CallOption) (*MsgDeleteInvoiceResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateParams_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) Storeinvoice(ctx context.Context, in *MsgStoreinvoice, opts ...grpc.CallOption) (*MsgStoreinvoiceResponse, error) {
	out := new(MsgStoreinvoiceResponse)
	err := c.cc.Invoke(ctx, Msg_Storeinvoice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateInvoice(ctx context.Context, in *MsgCreateInvoice, opts ...grpc.CallOption) (*MsgCreateInvoiceResponse, error) {
	out := new(MsgCreateInvoiceResponse)
	err := c.cc.Invoke(ctx, Msg_CreateInvoice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateInvoice(ctx context.Context, in *MsgUpdateInvoice, opts ...grpc.CallOption) (*MsgUpdateInvoiceResponse, error) {
	out := new(MsgUpdateInvoiceResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateInvoice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteInvoice(ctx context.Context, in *MsgDeleteInvoice, opts ...grpc.CallOption) (*MsgDeleteInvoiceResponse, error) {
	out := new(MsgDeleteInvoiceResponse)
	err := c.cc.Invoke(ctx, Msg_DeleteInvoice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility
type MsgServer interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	Storeinvoice(context.Context, *MsgStoreinvoice) (*MsgStoreinvoiceResponse, error)
	CreateInvoice(context.Context, *MsgCreateInvoice) (*MsgCreateInvoiceResponse, error)
	UpdateInvoice(context.Context, *MsgUpdateInvoice) (*MsgUpdateInvoiceResponse, error)
	DeleteInvoice(context.Context, *MsgDeleteInvoice) (*MsgDeleteInvoiceResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (UnimplementedMsgServer) UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (UnimplementedMsgServer) Storeinvoice(context.Context, *MsgStoreinvoice) (*MsgStoreinvoiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Storeinvoice not implemented")
}
func (UnimplementedMsgServer) CreateInvoice(context.Context, *MsgCreateInvoice) (*MsgCreateInvoiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateInvoice not implemented")
}
func (UnimplementedMsgServer) UpdateInvoice(context.Context, *MsgUpdateInvoice) (*MsgUpdateInvoiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateInvoice not implemented")
}
func (UnimplementedMsgServer) DeleteInvoice(context.Context, *MsgDeleteInvoice) (*MsgDeleteInvoiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteInvoice not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_Storeinvoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgStoreinvoice)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Storeinvoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_Storeinvoice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Storeinvoice(ctx, req.(*MsgStoreinvoice))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateInvoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateInvoice)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateInvoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_CreateInvoice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateInvoice(ctx, req.(*MsgCreateInvoice))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateInvoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateInvoice)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateInvoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateInvoice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateInvoice(ctx, req.(*MsgUpdateInvoice))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteInvoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteInvoice)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteInvoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_DeleteInvoice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteInvoice(ctx, req.(*MsgDeleteInvoice))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "invoice.invoice.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "Storeinvoice",
			Handler:    _Msg_Storeinvoice_Handler,
		},
		{
			MethodName: "CreateInvoice",
			Handler:    _Msg_CreateInvoice_Handler,
		},
		{
			MethodName: "UpdateInvoice",
			Handler:    _Msg_UpdateInvoice_Handler,
		},
		{
			MethodName: "DeleteInvoice",
			Handler:    _Msg_DeleteInvoice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "invoice/invoice/tx.proto",
}
