// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: invoice/invoice/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9498abebe6a566d5, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9498abebe6a566d5, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetInvoiceRequest struct {
	Creator        string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Index          string `protobuf:"bytes,2,opt,name=index,proto3" json:"index,omitempty"`
	Invoice_Number string `protobuf:"bytes,3,opt,name=Invoice_Number,json=InvoiceNumber,proto3" json:"Invoice_Number,omitempty"`
	Customer_Name  string `protobuf:"bytes,4,opt,name=Customer_Name,json=CustomerName,proto3" json:"Customer_Name,omitempty"`
	Invoice_Date   string `protobuf:"bytes,5,opt,name=Invoice_Date,json=InvoiceDate,proto3" json:"Invoice_Date,omitempty"`
	Total_Amount   string `protobuf:"bytes,6,opt,name=Total_Amount,json=TotalAmount,proto3" json:"Total_Amount,omitempty"`
	Due_Date       string `protobuf:"bytes,7,opt,name=Due_Date,json=DueDate,proto3" json:"Due_Date,omitempty"`
}

func (m *QueryGetInvoiceRequest) Reset()         { *m = QueryGetInvoiceRequest{} }
func (m *QueryGetInvoiceRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetInvoiceRequest) ProtoMessage()    {}
func (*QueryGetInvoiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9498abebe6a566d5, []int{2}
}
func (m *QueryGetInvoiceRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetInvoiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetInvoiceRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetInvoiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetInvoiceRequest.Merge(m, src)
}
func (m *QueryGetInvoiceRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetInvoiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetInvoiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetInvoiceRequest proto.InternalMessageInfo

func (m *QueryGetInvoiceRequest) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *QueryGetInvoiceRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *QueryGetInvoiceRequest) GetInvoice_Number() string {
	if m != nil {
		return m.Invoice_Number
	}
	return ""
}

func (m *QueryGetInvoiceRequest) GetCustomer_Name() string {
	if m != nil {
		return m.Customer_Name
	}
	return ""
}

func (m *QueryGetInvoiceRequest) GetInvoice_Date() string {
	if m != nil {
		return m.Invoice_Date
	}
	return ""
}

func (m *QueryGetInvoiceRequest) GetTotal_Amount() string {
	if m != nil {
		return m.Total_Amount
	}
	return ""
}

func (m *QueryGetInvoiceRequest) GetDue_Date() string {
	if m != nil {
		return m.Due_Date
	}
	return ""
}

type QueryGetInvoiceResponse struct {
	Invoice Invoice `protobuf:"bytes,1,opt,name=invoice,proto3" json:"invoice"`
}

func (m *QueryGetInvoiceResponse) Reset()         { *m = QueryGetInvoiceResponse{} }
func (m *QueryGetInvoiceResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetInvoiceResponse) ProtoMessage()    {}
func (*QueryGetInvoiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9498abebe6a566d5, []int{3}
}
func (m *QueryGetInvoiceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetInvoiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetInvoiceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetInvoiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetInvoiceResponse.Merge(m, src)
}
func (m *QueryGetInvoiceResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetInvoiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetInvoiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetInvoiceResponse proto.InternalMessageInfo

func (m *QueryGetInvoiceResponse) GetInvoice() Invoice {
	if m != nil {
		return m.Invoice
	}
	return Invoice{}
}

type QueryAllInvoiceRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllInvoiceRequest) Reset()         { *m = QueryAllInvoiceRequest{} }
func (m *QueryAllInvoiceRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllInvoiceRequest) ProtoMessage()    {}
func (*QueryAllInvoiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9498abebe6a566d5, []int{4}
}
func (m *QueryAllInvoiceRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllInvoiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllInvoiceRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllInvoiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllInvoiceRequest.Merge(m, src)
}
func (m *QueryAllInvoiceRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllInvoiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllInvoiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllInvoiceRequest proto.InternalMessageInfo

func (m *QueryAllInvoiceRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllInvoiceResponse struct {
	Invoice    []Invoice           `protobuf:"bytes,1,rep,name=invoice,proto3" json:"invoice"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllInvoiceResponse) Reset()         { *m = QueryAllInvoiceResponse{} }
func (m *QueryAllInvoiceResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllInvoiceResponse) ProtoMessage()    {}
func (*QueryAllInvoiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9498abebe6a566d5, []int{5}
}
func (m *QueryAllInvoiceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllInvoiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllInvoiceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllInvoiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllInvoiceResponse.Merge(m, src)
}
func (m *QueryAllInvoiceResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllInvoiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllInvoiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllInvoiceResponse proto.InternalMessageInfo

func (m *QueryAllInvoiceResponse) GetInvoice() []Invoice {
	if m != nil {
		return m.Invoice
	}
	return nil
}

func (m *QueryAllInvoiceResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "invoice.invoice.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "invoice.invoice.QueryParamsResponse")
	proto.RegisterType((*QueryGetInvoiceRequest)(nil), "invoice.invoice.QueryGetInvoiceRequest")
	proto.RegisterType((*QueryGetInvoiceResponse)(nil), "invoice.invoice.QueryGetInvoiceResponse")
	proto.RegisterType((*QueryAllInvoiceRequest)(nil), "invoice.invoice.QueryAllInvoiceRequest")
	proto.RegisterType((*QueryAllInvoiceResponse)(nil), "invoice.invoice.QueryAllInvoiceResponse")
}

func init() { proto.RegisterFile("invoice/invoice/query.proto", fileDescriptor_9498abebe6a566d5) }

var fileDescriptor_9498abebe6a566d5 = []byte{
	// 594 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xb1, 0x6f, 0xd3, 0x4e,
	0x18, 0x8d, 0x93, 0x26, 0xf9, 0xf5, 0xda, 0xfe, 0x10, 0x47, 0x44, 0xdc, 0x00, 0x6e, 0x70, 0x81,
	0x46, 0x1d, 0x7c, 0x4a, 0x59, 0x10, 0x5b, 0x42, 0x44, 0xc5, 0x52, 0xb5, 0x81, 0x89, 0x25, 0x5c,
	0xc2, 0xc9, 0xb2, 0x64, 0xfb, 0x5c, 0xfb, 0x5c, 0xb5, 0x42, 0x0c, 0x30, 0x30, 0x30, 0x21, 0xb1,
	0xf2, 0x07, 0x30, 0xf2, 0x67, 0x74, 0xac, 0xc4, 0xc2, 0x84, 0x50, 0x82, 0xc4, 0x5f, 0xc0, 0x8e,
	0x7c, 0xf7, 0x1d, 0xa4, 0x71, 0x42, 0xc5, 0x12, 0xfb, 0xde, 0xbd, 0xef, 0x7d, 0xef, 0xbe, 0xbc,
	0x33, 0xba, 0xe6, 0x85, 0x47, 0xdc, 0x1b, 0x31, 0xa2, 0x9f, 0x87, 0x29, 0x8b, 0x4f, 0x9c, 0x28,
	0xe6, 0x82, 0xe3, 0x4b, 0x00, 0x3a, 0xf0, 0x6c, 0x5c, 0xa6, 0x81, 0x17, 0x72, 0x22, 0x7f, 0x15,
	0xa7, 0x51, 0x73, 0xb9, 0xcb, 0xe5, 0x2b, 0xc9, 0xde, 0x00, 0xbd, 0xee, 0x72, 0xee, 0xfa, 0x8c,
	0xd0, 0xc8, 0x23, 0x34, 0x0c, 0xb9, 0xa0, 0xc2, 0xe3, 0x61, 0x02, 0xbb, 0xdb, 0x23, 0x9e, 0x04,
	0x3c, 0x21, 0x43, 0x9a, 0x40, 0x43, 0x72, 0xd4, 0x1e, 0x32, 0x41, 0xdb, 0x24, 0xa2, 0xae, 0x17,
	0x4a, 0xb2, 0x56, 0x9a, 0x35, 0x18, 0xd1, 0x98, 0x06, 0x5a, 0xe9, 0xc6, 0xec, 0xae, 0x76, 0x2c,
	0xb7, 0xed, 0x1a, 0xc2, 0x07, 0x99, 0xfc, 0xbe, 0xac, 0xe9, 0xb3, 0xc3, 0x94, 0x25, 0xc2, 0x3e,
	0x40, 0x57, 0xce, 0xa1, 0x49, 0xc4, 0xc3, 0x84, 0xe1, 0xfb, 0xa8, 0xa2, 0xb4, 0x4d, 0xa3, 0x69,
	0xb4, 0x56, 0x76, 0xea, 0xce, 0xcc, 0xf1, 0x1d, 0x55, 0xd0, 0x5d, 0x3e, 0xfd, 0xba, 0x51, 0xf8,
	0xf8, 0xe3, 0xd3, 0xb6, 0xd1, 0x87, 0x0a, 0xfb, 0xa7, 0x81, 0xae, 0x4a, 0xcd, 0x5d, 0x26, 0x1e,
	0x29, 0x36, 0x74, 0xc3, 0x26, 0xaa, 0x8e, 0x62, 0x46, 0x05, 0x8f, 0xa5, 0xee, 0x72, 0x5f, 0x2f,
	0x71, 0x0d, 0x95, 0xbd, 0xf0, 0x39, 0x3b, 0x36, 0x8b, 0x12, 0x57, 0x0b, 0x7c, 0x1b, 0xfd, 0x0f,
	0x0a, 0x83, 0xbd, 0x34, 0x18, 0xb2, 0xd8, 0x2c, 0xc9, 0xed, 0x35, 0x40, 0x15, 0x88, 0x37, 0xd1,
	0xda, 0x83, 0x34, 0x11, 0x3c, 0x60, 0xf1, 0x60, 0x8f, 0x06, 0xcc, 0x5c, 0x92, 0xac, 0x55, 0x0d,
	0x66, 0x18, 0xbe, 0x89, 0x56, 0xb5, 0x56, 0x8f, 0x0a, 0x66, 0x96, 0x25, 0x67, 0x05, 0xb0, 0x0c,
	0xca, 0x28, 0x4f, 0xb8, 0xa0, 0xfe, 0xa0, 0x13, 0xf0, 0x34, 0x14, 0x66, 0x45, 0x51, 0x24, 0xa6,
	0x20, 0xbc, 0x8e, 0xfe, 0xeb, 0xa5, 0xa0, 0x50, 0x55, 0x47, 0xe8, 0xa5, 0xb2, 0xda, 0x7e, 0x8c,
	0xea, 0xb9, 0x63, 0xc3, 0x38, 0xef, 0xa1, 0x2a, 0xcc, 0x0d, 0xe6, 0x69, 0xe6, 0xe6, 0x09, 0x25,
	0xdd, 0xa5, 0x6c, 0xa0, 0x7d, 0x4d, 0xb7, 0x9f, 0xc1, 0x2c, 0x3b, 0xbe, 0x3f, 0x33, 0xcb, 0x87,
	0x08, 0xfd, 0x09, 0x08, 0xc8, 0xde, 0x71, 0x54, 0x9a, 0x9c, 0x2c, 0x4d, 0x8e, 0x8a, 0x2f, 0xa4,
	0xc9, 0xd9, 0xa7, 0xae, 0xae, 0xed, 0x4f, 0x55, 0xda, 0x1f, 0x0c, 0xf0, 0x3d, 0xdd, 0x62, 0x9e,
	0xef, 0xd2, 0x3f, 0xf8, 0xc6, 0xbb, 0xe7, 0xdc, 0x15, 0xa5, 0xbb, 0xad, 0x0b, 0xdd, 0xa9, 0xb6,
	0xd3, 0xf6, 0x76, 0xde, 0x96, 0x50, 0x59, 0xda, 0xc3, 0x02, 0x55, 0x54, 0xe8, 0xf0, 0x66, 0xce,
	0x45, 0x3e, 0xd9, 0x8d, 0x5b, 0x7f, 0x27, 0xa9, 0x56, 0xf6, 0xc6, 0xeb, 0xcf, 0xdf, 0xdf, 0x17,
	0xd7, 0x71, 0x9d, 0xcc, 0xbf, 0x5b, 0xf8, 0x8d, 0x81, 0xaa, 0x70, 0x46, 0xbc, 0x35, 0x5f, 0x32,
	0x97, 0xf3, 0x46, 0xeb, 0x62, 0x22, 0xf4, 0x6f, 0xc9, 0xfe, 0x36, 0x6e, 0x92, 0x05, 0xb7, 0x97,
	0xbc, 0x90, 0x57, 0xe1, 0x25, 0x7e, 0x65, 0x20, 0x04, 0xd5, 0x1d, 0xdf, 0x5f, 0xe4, 0x25, 0x97,
	0x93, 0x45, 0x5e, 0xf2, 0xff, 0xb6, 0xdd, 0x94, 0x5e, 0x1a, 0xd8, 0x5c, 0xe4, 0xa5, 0xdb, 0x3e,
	0x1d, 0x5b, 0xc6, 0xd9, 0xd8, 0x32, 0xbe, 0x8d, 0x2d, 0xe3, 0xdd, 0xc4, 0x2a, 0x9c, 0x4d, 0xac,
	0xc2, 0x97, 0x89, 0x55, 0x78, 0x5a, 0xd7, 0xd4, 0xe3, 0xdf, 0x45, 0xe2, 0x24, 0x62, 0xc9, 0xb0,
	0x22, 0xbf, 0x3e, 0x77, 0x7f, 0x05, 0x00, 0x00, 0xff, 0xff, 0x0f, 0xd5, 0x77, 0x19, 0x5d, 0x05,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of Invoice items.
	Invoice(ctx context.Context, in *QueryGetInvoiceRequest, opts ...grpc.CallOption) (*QueryGetInvoiceResponse, error)
	InvoiceAll(ctx context.Context, in *QueryAllInvoiceRequest, opts ...grpc.CallOption) (*QueryAllInvoiceResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/invoice.invoice.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Invoice(ctx context.Context, in *QueryGetInvoiceRequest, opts ...grpc.CallOption) (*QueryGetInvoiceResponse, error) {
	out := new(QueryGetInvoiceResponse)
	err := c.cc.Invoke(ctx, "/invoice.invoice.Query/Invoice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) InvoiceAll(ctx context.Context, in *QueryAllInvoiceRequest, opts ...grpc.CallOption) (*QueryAllInvoiceResponse, error) {
	out := new(QueryAllInvoiceResponse)
	err := c.cc.Invoke(ctx, "/invoice.invoice.Query/InvoiceAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of Invoice items.
	Invoice(context.Context, *QueryGetInvoiceRequest) (*QueryGetInvoiceResponse, error)
	InvoiceAll(context.Context, *QueryAllInvoiceRequest) (*QueryAllInvoiceResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) Invoice(ctx context.Context, req *QueryGetInvoiceRequest) (*QueryGetInvoiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invoice not implemented")
}
func (*UnimplementedQueryServer) InvoiceAll(ctx context.Context, req *QueryAllInvoiceRequest) (*QueryAllInvoiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InvoiceAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/invoice.invoice.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Invoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetInvoiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Invoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/invoice.invoice.Query/Invoice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Invoice(ctx, req.(*QueryGetInvoiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_InvoiceAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllInvoiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).InvoiceAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/invoice.invoice.Query/InvoiceAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).InvoiceAll(ctx, req.(*QueryAllInvoiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "invoice.invoice.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Invoice",
			Handler:    _Query_Invoice_Handler,
		},
		{
			MethodName: "InvoiceAll",
			Handler:    _Query_InvoiceAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "invoice/invoice/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetInvoiceRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetInvoiceRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetInvoiceRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Due_Date) > 0 {
		i -= len(m.Due_Date)
		copy(dAtA[i:], m.Due_Date)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Due_Date)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Total_Amount) > 0 {
		i -= len(m.Total_Amount)
		copy(dAtA[i:], m.Total_Amount)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Total_Amount)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Invoice_Date) > 0 {
		i -= len(m.Invoice_Date)
		copy(dAtA[i:], m.Invoice_Date)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Invoice_Date)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Customer_Name) > 0 {
		i -= len(m.Customer_Name)
		copy(dAtA[i:], m.Customer_Name)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Customer_Name)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Invoice_Number) > 0 {
		i -= len(m.Invoice_Number)
		copy(dAtA[i:], m.Invoice_Number)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Invoice_Number)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetInvoiceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetInvoiceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetInvoiceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Invoice.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllInvoiceRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllInvoiceRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllInvoiceRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllInvoiceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllInvoiceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllInvoiceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Invoice) > 0 {
		for iNdEx := len(m.Invoice) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Invoice[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetInvoiceRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Invoice_Number)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Customer_Name)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Invoice_Date)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Total_Amount)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Due_Date)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetInvoiceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Invoice.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllInvoiceRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllInvoiceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Invoice) > 0 {
		for _, e := range m.Invoice {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetInvoiceRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetInvoiceRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetInvoiceRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Invoice_Number", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Invoice_Number = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Customer_Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Customer_Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Invoice_Date", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Invoice_Date = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Total_Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Total_Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Due_Date", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Due_Date = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetInvoiceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetInvoiceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetInvoiceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Invoice", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Invoice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllInvoiceRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllInvoiceRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllInvoiceRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllInvoiceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllInvoiceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllInvoiceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Invoice", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Invoice = append(m.Invoice, Invoice{})
			if err := m.Invoice[len(m.Invoice)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
