// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: invoice/invoice/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgUpdateParams is the Msg/UpdateParams request type.
type MsgUpdateParams struct {
	// authority is the address that controls the module (defaults to x/gov unless overwritten).
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// NOTE: All parameters must be supplied.
	Params Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_76672f4abcfa6eb6, []int{0}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// MsgUpdateParamsResponse defines the response structure for executing a
// MsgUpdateParams message.
type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_76672f4abcfa6eb6, []int{1}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

type MsgStoreinvoice struct {
	Creator        string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Index          string `protobuf:"bytes,2,opt,name=index,proto3" json:"index,omitempty"`
	Invoice_Number string `protobuf:"bytes,3,opt,name=Invoice_Number,json=InvoiceNumber,proto3" json:"Invoice_Number,omitempty"`
	Customer_Name  string `protobuf:"bytes,4,opt,name=Customer_Name,json=CustomerName,proto3" json:"Customer_Name,omitempty"`
	Invoice_Date   string `protobuf:"bytes,5,opt,name=Invoice_Date,json=InvoiceDate,proto3" json:"Invoice_Date,omitempty"`
	Total_Amount   string `protobuf:"bytes,6,opt,name=Total_Amount,json=TotalAmount,proto3" json:"Total_Amount,omitempty"`
	Due_Date       string `protobuf:"bytes,7,opt,name=Due_Date,json=DueDate,proto3" json:"Due_Date,omitempty"`
}

func (m *MsgStoreinvoice) Reset()         { *m = MsgStoreinvoice{} }
func (m *MsgStoreinvoice) String() string { return proto.CompactTextString(m) }
func (*MsgStoreinvoice) ProtoMessage()    {}
func (*MsgStoreinvoice) Descriptor() ([]byte, []int) {
	return fileDescriptor_76672f4abcfa6eb6, []int{2}
}
func (m *MsgStoreinvoice) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgStoreinvoice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgStoreinvoice.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgStoreinvoice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgStoreinvoice.Merge(m, src)
}
func (m *MsgStoreinvoice) XXX_Size() int {
	return m.Size()
}
func (m *MsgStoreinvoice) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgStoreinvoice.DiscardUnknown(m)
}

var xxx_messageInfo_MsgStoreinvoice proto.InternalMessageInfo

func (m *MsgStoreinvoice) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgStoreinvoice) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *MsgStoreinvoice) GetInvoice_Number() string {
	if m != nil {
		return m.Invoice_Number
	}
	return ""
}

func (m *MsgStoreinvoice) GetCustomer_Name() string {
	if m != nil {
		return m.Customer_Name
	}
	return ""
}

func (m *MsgStoreinvoice) GetInvoice_Date() string {
	if m != nil {
		return m.Invoice_Date
	}
	return ""
}

func (m *MsgStoreinvoice) GetTotal_Amount() string {
	if m != nil {
		return m.Total_Amount
	}
	return ""
}

func (m *MsgStoreinvoice) GetDue_Date() string {
	if m != nil {
		return m.Due_Date
	}
	return ""
}

type MsgStoreinvoiceResponse struct {
}

func (m *MsgStoreinvoiceResponse) Reset()         { *m = MsgStoreinvoiceResponse{} }
func (m *MsgStoreinvoiceResponse) String() string { return proto.CompactTextString(m) }
func (*MsgStoreinvoiceResponse) ProtoMessage()    {}
func (*MsgStoreinvoiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_76672f4abcfa6eb6, []int{3}
}
func (m *MsgStoreinvoiceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgStoreinvoiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgStoreinvoiceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgStoreinvoiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgStoreinvoiceResponse.Merge(m, src)
}
func (m *MsgStoreinvoiceResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgStoreinvoiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgStoreinvoiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgStoreinvoiceResponse proto.InternalMessageInfo

type MsgCreateInvoice struct {
	Creator        string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Index          string `protobuf:"bytes,2,opt,name=index,proto3" json:"index,omitempty"`
	Invoice_Number string `protobuf:"bytes,3,opt,name=Invoice_Number,json=InvoiceNumber,proto3" json:"Invoice_Number,omitempty"`
	Customer_Name  string `protobuf:"bytes,4,opt,name=Customer_Name,json=CustomerName,proto3" json:"Customer_Name,omitempty"`
	Invoice_Date   string `protobuf:"bytes,5,opt,name=Invoice_Date,json=InvoiceDate,proto3" json:"Invoice_Date,omitempty"`
	Total_Amount   string `protobuf:"bytes,6,opt,name=Total_Amount,json=TotalAmount,proto3" json:"Total_Amount,omitempty"`
	Due_Date       string `protobuf:"bytes,7,opt,name=Due_Date,json=DueDate,proto3" json:"Due_Date,omitempty"`
}

func (m *MsgCreateInvoice) Reset()         { *m = MsgCreateInvoice{} }
func (m *MsgCreateInvoice) String() string { return proto.CompactTextString(m) }
func (*MsgCreateInvoice) ProtoMessage()    {}
func (*MsgCreateInvoice) Descriptor() ([]byte, []int) {
	return fileDescriptor_76672f4abcfa6eb6, []int{4}
}
func (m *MsgCreateInvoice) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateInvoice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateInvoice.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateInvoice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateInvoice.Merge(m, src)
}
func (m *MsgCreateInvoice) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateInvoice) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateInvoice.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateInvoice proto.InternalMessageInfo

func (m *MsgCreateInvoice) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateInvoice) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *MsgCreateInvoice) GetInvoice_Number() string {
	if m != nil {
		return m.Invoice_Number
	}
	return ""
}

func (m *MsgCreateInvoice) GetCustomer_Name() string {
	if m != nil {
		return m.Customer_Name
	}
	return ""
}

func (m *MsgCreateInvoice) GetInvoice_Date() string {
	if m != nil {
		return m.Invoice_Date
	}
	return ""
}

func (m *MsgCreateInvoice) GetTotal_Amount() string {
	if m != nil {
		return m.Total_Amount
	}
	return ""
}

func (m *MsgCreateInvoice) GetDue_Date() string {
	if m != nil {
		return m.Due_Date
	}
	return ""
}

type MsgCreateInvoiceResponse struct {
}

func (m *MsgCreateInvoiceResponse) Reset()         { *m = MsgCreateInvoiceResponse{} }
func (m *MsgCreateInvoiceResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateInvoiceResponse) ProtoMessage()    {}
func (*MsgCreateInvoiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_76672f4abcfa6eb6, []int{5}
}
func (m *MsgCreateInvoiceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateInvoiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateInvoiceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateInvoiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateInvoiceResponse.Merge(m, src)
}
func (m *MsgCreateInvoiceResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateInvoiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateInvoiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateInvoiceResponse proto.InternalMessageInfo

type MsgUpdateInvoice struct {
	Creator        string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Index          string `protobuf:"bytes,2,opt,name=index,proto3" json:"index,omitempty"`
	Invoice_Number string `protobuf:"bytes,3,opt,name=Invoice_Number,json=InvoiceNumber,proto3" json:"Invoice_Number,omitempty"`
	Customer_Name  string `protobuf:"bytes,4,opt,name=Customer_Name,json=CustomerName,proto3" json:"Customer_Name,omitempty"`
	Invoice_Date   string `protobuf:"bytes,5,opt,name=Invoice_Date,json=InvoiceDate,proto3" json:"Invoice_Date,omitempty"`
	Total_Amount   string `protobuf:"bytes,6,opt,name=Total_Amount,json=TotalAmount,proto3" json:"Total_Amount,omitempty"`
	Due_Date       string `protobuf:"bytes,7,opt,name=Due_Date,json=DueDate,proto3" json:"Due_Date,omitempty"`
}

func (m *MsgUpdateInvoice) Reset()         { *m = MsgUpdateInvoice{} }
func (m *MsgUpdateInvoice) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateInvoice) ProtoMessage()    {}
func (*MsgUpdateInvoice) Descriptor() ([]byte, []int) {
	return fileDescriptor_76672f4abcfa6eb6, []int{6}
}
func (m *MsgUpdateInvoice) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateInvoice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateInvoice.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateInvoice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateInvoice.Merge(m, src)
}
func (m *MsgUpdateInvoice) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateInvoice) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateInvoice.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateInvoice proto.InternalMessageInfo

func (m *MsgUpdateInvoice) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgUpdateInvoice) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *MsgUpdateInvoice) GetInvoice_Number() string {
	if m != nil {
		return m.Invoice_Number
	}
	return ""
}

func (m *MsgUpdateInvoice) GetCustomer_Name() string {
	if m != nil {
		return m.Customer_Name
	}
	return ""
}

func (m *MsgUpdateInvoice) GetInvoice_Date() string {
	if m != nil {
		return m.Invoice_Date
	}
	return ""
}

func (m *MsgUpdateInvoice) GetTotal_Amount() string {
	if m != nil {
		return m.Total_Amount
	}
	return ""
}

func (m *MsgUpdateInvoice) GetDue_Date() string {
	if m != nil {
		return m.Due_Date
	}
	return ""
}

type MsgUpdateInvoiceResponse struct {
}

func (m *MsgUpdateInvoiceResponse) Reset()         { *m = MsgUpdateInvoiceResponse{} }
func (m *MsgUpdateInvoiceResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateInvoiceResponse) ProtoMessage()    {}
func (*MsgUpdateInvoiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_76672f4abcfa6eb6, []int{7}
}
func (m *MsgUpdateInvoiceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateInvoiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateInvoiceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateInvoiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateInvoiceResponse.Merge(m, src)
}
func (m *MsgUpdateInvoiceResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateInvoiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateInvoiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateInvoiceResponse proto.InternalMessageInfo

type MsgDeleteInvoice struct {
	Creator        string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Index          string `protobuf:"bytes,2,opt,name=index,proto3" json:"index,omitempty"`
	Invoice_Number string `protobuf:"bytes,3,opt,name=Invoice_Number,json=InvoiceNumber,proto3" json:"Invoice_Number,omitempty"`
	Customer_Name  string `protobuf:"bytes,4,opt,name=Customer_Name,json=CustomerName,proto3" json:"Customer_Name,omitempty"`
	Invoice_Date   string `protobuf:"bytes,5,opt,name=Invoice_Date,json=InvoiceDate,proto3" json:"Invoice_Date,omitempty"`
	Total_Amount   string `protobuf:"bytes,6,opt,name=Total_Amount,json=TotalAmount,proto3" json:"Total_Amount,omitempty"`
	Due_Date       string `protobuf:"bytes,7,opt,name=Due_Date,json=DueDate,proto3" json:"Due_Date,omitempty"`
}

func (m *MsgDeleteInvoice) Reset()         { *m = MsgDeleteInvoice{} }
func (m *MsgDeleteInvoice) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteInvoice) ProtoMessage()    {}
func (*MsgDeleteInvoice) Descriptor() ([]byte, []int) {
	return fileDescriptor_76672f4abcfa6eb6, []int{8}
}
func (m *MsgDeleteInvoice) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteInvoice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteInvoice.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteInvoice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteInvoice.Merge(m, src)
}
func (m *MsgDeleteInvoice) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteInvoice) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteInvoice.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteInvoice proto.InternalMessageInfo

func (m *MsgDeleteInvoice) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgDeleteInvoice) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *MsgDeleteInvoice) GetInvoice_Number() string {
	if m != nil {
		return m.Invoice_Number
	}
	return ""
}

func (m *MsgDeleteInvoice) GetCustomer_Name() string {
	if m != nil {
		return m.Customer_Name
	}
	return ""
}

func (m *MsgDeleteInvoice) GetInvoice_Date() string {
	if m != nil {
		return m.Invoice_Date
	}
	return ""
}

func (m *MsgDeleteInvoice) GetTotal_Amount() string {
	if m != nil {
		return m.Total_Amount
	}
	return ""
}

func (m *MsgDeleteInvoice) GetDue_Date() string {
	if m != nil {
		return m.Due_Date
	}
	return ""
}

type MsgDeleteInvoiceResponse struct {
}

func (m *MsgDeleteInvoiceResponse) Reset()         { *m = MsgDeleteInvoiceResponse{} }
func (m *MsgDeleteInvoiceResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteInvoiceResponse) ProtoMessage()    {}
func (*MsgDeleteInvoiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_76672f4abcfa6eb6, []int{9}
}
func (m *MsgDeleteInvoiceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteInvoiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteInvoiceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteInvoiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteInvoiceResponse.Merge(m, src)
}
func (m *MsgDeleteInvoiceResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteInvoiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteInvoiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteInvoiceResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgUpdateParams)(nil), "invoice.invoice.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "invoice.invoice.MsgUpdateParamsResponse")
	proto.RegisterType((*MsgStoreinvoice)(nil), "invoice.invoice.MsgStoreinvoice")
	proto.RegisterType((*MsgStoreinvoiceResponse)(nil), "invoice.invoice.MsgStoreinvoiceResponse")
	proto.RegisterType((*MsgCreateInvoice)(nil), "invoice.invoice.MsgCreateInvoice")
	proto.RegisterType((*MsgCreateInvoiceResponse)(nil), "invoice.invoice.MsgCreateInvoiceResponse")
	proto.RegisterType((*MsgUpdateInvoice)(nil), "invoice.invoice.MsgUpdateInvoice")
	proto.RegisterType((*MsgUpdateInvoiceResponse)(nil), "invoice.invoice.MsgUpdateInvoiceResponse")
	proto.RegisterType((*MsgDeleteInvoice)(nil), "invoice.invoice.MsgDeleteInvoice")
	proto.RegisterType((*MsgDeleteInvoiceResponse)(nil), "invoice.invoice.MsgDeleteInvoiceResponse")
}

func init() { proto.RegisterFile("invoice/invoice/tx.proto", fileDescriptor_76672f4abcfa6eb6) }

var fileDescriptor_76672f4abcfa6eb6 = []byte{
	// 579 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x55, 0x4f, 0x6f, 0x12, 0x41,
	0x14, 0x67, 0x45, 0xa8, 0x4c, 0xc1, 0xea, 0x84, 0x84, 0x65, 0xa3, 0x2b, 0x60, 0x4c, 0x90, 0x44,
	0x48, 0xab, 0xf1, 0xc0, 0xad, 0x94, 0x4b, 0x0f, 0x34, 0x86, 0xea, 0xa5, 0x89, 0x21, 0x5b, 0x98,
	0xac, 0x9b, 0x74, 0x77, 0x36, 0x33, 0xb3, 0x0d, 0xbd, 0x19, 0x8f, 0x9e, 0xfc, 0x18, 0x1e, 0x39,
	0x78, 0xf3, 0x0b, 0xf4, 0xd8, 0x78, 0xf2, 0x64, 0x14, 0x0e, 0x7c, 0x09, 0x4d, 0xcc, 0xfc, 0x6b,
	0xd9, 0xed, 0x6a, 0x3f, 0x00, 0x17, 0x86, 0xf9, 0xbd, 0xdf, 0xfb, 0xcd, 0x7b, 0x3f, 0x86, 0x37,
	0xc0, 0xf4, 0x82, 0x53, 0xec, 0x8d, 0x51, 0x47, 0xaf, 0x6c, 0xda, 0x0e, 0x09, 0x66, 0x18, 0x6e,
	0x29, 0xa4, 0xad, 0x56, 0xeb, 0xbe, 0xe3, 0x7b, 0x01, 0xee, 0x88, 0x4f, 0xc9, 0xb1, 0x2a, 0x63,
	0x4c, 0x7d, 0x4c, 0x3b, 0x3e, 0x75, 0x3b, 0xa7, 0xdb, 0x7c, 0x51, 0x81, 0xaa, 0x0c, 0x8c, 0xc4,
	0xae, 0x23, 0x37, 0x2a, 0x54, 0x76, 0xb1, 0x8b, 0x25, 0xce, 0xbf, 0x29, 0xf4, 0x41, 0xb2, 0x8e,
	0xd0, 0x21, 0x8e, 0xaf, 0x73, 0x1e, 0x26, 0xa3, 0xba, 0x36, 0x11, 0x6e, 0x7c, 0x35, 0xc0, 0xd6,
	0x80, 0xba, 0x6f, 0xc2, 0x89, 0xc3, 0xd0, 0x2b, 0x91, 0x08, 0x5f, 0x82, 0x82, 0x13, 0xb1, 0x77,
	0x98, 0x78, 0xec, 0xcc, 0x34, 0x6a, 0x46, 0xb3, 0xd0, 0x33, 0xbf, 0x7d, 0x79, 0x56, 0x56, 0xb5,
	0xec, 0x4e, 0x26, 0x04, 0x51, 0x7a, 0xc8, 0x88, 0x17, 0xb8, 0xc3, 0x2b, 0x2a, 0xec, 0x82, 0xbc,
	0x3c, 0xda, 0xbc, 0x55, 0x33, 0x9a, 0x9b, 0x3b, 0x95, 0x76, 0xc2, 0x87, 0xb6, 0x3c, 0xa0, 0x57,
	0x38, 0xff, 0xf1, 0x28, 0xf3, 0x79, 0x39, 0x6b, 0x19, 0x43, 0x95, 0xd1, 0x7d, 0xf1, 0x61, 0x39,
	0x6b, 0x5d, 0x69, 0x7d, 0x5c, 0xce, 0x5a, 0x75, 0x5d, 0xf1, 0xf4, 0xb2, 0xf6, 0x44, 0xa5, 0x8d,
	0x2a, 0xa8, 0x24, 0xa0, 0x21, 0xa2, 0x21, 0x0e, 0x28, 0x6a, 0xfc, 0x96, 0x8d, 0x1d, 0x32, 0x4c,
	0x90, 0x4a, 0x87, 0x26, 0xd8, 0x18, 0x13, 0xe4, 0x30, 0x4c, 0x64, 0x5b, 0x43, 0xbd, 0x85, 0x65,
	0x90, 0xf3, 0x82, 0x09, 0x9a, 0x8a, 0xca, 0x0b, 0x43, 0xb9, 0x81, 0x4f, 0xc0, 0xdd, 0x7d, 0x99,
	0x3a, 0x3a, 0x88, 0xfc, 0x63, 0x44, 0xcc, 0xac, 0x08, 0x97, 0x14, 0x2a, 0x41, 0xf8, 0x18, 0x94,
	0xf6, 0x22, 0xca, 0xb0, 0x8f, 0xc8, 0xe8, 0xc0, 0xf1, 0x91, 0x79, 0x5b, 0xb0, 0x8a, 0x1a, 0xe4,
	0x18, 0xac, 0x83, 0xa2, 0xd6, 0xea, 0x3b, 0x0c, 0x99, 0x39, 0xc1, 0xd9, 0x54, 0x18, 0x87, 0x38,
	0xe5, 0x35, 0x66, 0xce, 0xc9, 0x68, 0xd7, 0xc7, 0x51, 0xc0, 0xcc, 0xbc, 0xa4, 0x08, 0x4c, 0x42,
	0xb0, 0x0a, 0xee, 0xf4, 0x23, 0xa5, 0xb0, 0x21, 0x5b, 0xe8, 0x47, 0x22, 0xbb, 0x5b, 0xe4, 0x0e,
	0xea, 0x86, 0x94, 0x33, 0xab, 0xdd, 0x5f, 0x3a, 0xf3, 0xc7, 0x00, 0xf7, 0x06, 0xd4, 0xdd, 0xe3,
	0x4c, 0xb4, 0xbf, 0x7e, 0xd6, 0x58, 0xc0, 0x4c, 0xb6, 0x9f, 0xf4, 0x46, 0xde, 0xa8, 0xb5, 0xf5,
	0x26, 0xd6, 0x7e, 0xd2, 0x9b, 0x3e, 0x3a, 0x41, 0x6b, 0xec, 0x4d, 0xac, 0x7d, 0xed, 0xcd, 0xce,
	0xaf, 0x2c, 0xc8, 0x0e, 0xa8, 0x0b, 0x8f, 0x40, 0x31, 0x36, 0x4a, 0x6b, 0xd7, 0x46, 0x60, 0x62,
	0x5e, 0x59, 0xcd, 0x9b, 0x18, 0xfa, 0x0c, 0xae, 0x1d, 0x9b, 0x66, 0xa9, 0xda, 0xab, 0x8c, 0x74,
	0xed, 0xb4, 0x99, 0x00, 0xdf, 0x82, 0x52, 0x7c, 0x1e, 0xd4, 0xd3, 0x52, 0x63, 0x14, 0xeb, 0xe9,
	0x8d, 0x94, 0x55, 0xf9, 0xf8, 0x5f, 0xaa, 0xfe, 0xef, 0xae, 0xff, 0x2b, 0x9f, 0x7a, 0x33, 0xb9,
	0x7c, 0xfc, 0x56, 0xa6, 0xca, 0xc7, 0x28, 0xe9, 0xf2, 0xa9, 0x3f, 0xae, 0x95, 0x7b, 0xcf, 0x9f,
	0xaa, 0xde, 0xf6, 0xf9, 0xdc, 0x36, 0x2e, 0xe6, 0xb6, 0xf1, 0x73, 0x6e, 0x1b, 0x9f, 0x16, 0x76,
	0xe6, 0x62, 0x61, 0x67, 0xbe, 0x2f, 0xec, 0xcc, 0x51, 0xe5, 0xfa, 0x4b, 0xc5, 0xce, 0x42, 0x44,
	0x8f, 0xf3, 0xe2, 0x91, 0x7d, 0xfe, 0x37, 0x00, 0x00, 0xff, 0xff, 0x85, 0x78, 0x43, 0x06, 0x2b,
	0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	Storeinvoice(ctx context.Context, in *MsgStoreinvoice, opts ...grpc.CallOption) (*MsgStoreinvoiceResponse, error)
	CreateInvoice(ctx context.Context, in *MsgCreateInvoice, opts ...grpc.CallOption) (*MsgCreateInvoiceResponse, error)
	UpdateInvoice(ctx context.Context, in *MsgUpdateInvoice, opts ...grpc.CallOption) (*MsgUpdateInvoiceResponse, error)
	DeleteInvoice(ctx context.Context, in *MsgDeleteInvoice, opts ...grpc.CallOption) (*MsgDeleteInvoiceResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/invoice.invoice.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) Storeinvoice(ctx context.Context, in *MsgStoreinvoice, opts ...grpc.CallOption) (*MsgStoreinvoiceResponse, error) {
	out := new(MsgStoreinvoiceResponse)
	err := c.cc.Invoke(ctx, "/invoice.invoice.Msg/Storeinvoice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateInvoice(ctx context.Context, in *MsgCreateInvoice, opts ...grpc.CallOption) (*MsgCreateInvoiceResponse, error) {
	out := new(MsgCreateInvoiceResponse)
	err := c.cc.Invoke(ctx, "/invoice.invoice.Msg/CreateInvoice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateInvoice(ctx context.Context, in *MsgUpdateInvoice, opts ...grpc.CallOption) (*MsgUpdateInvoiceResponse, error) {
	out := new(MsgUpdateInvoiceResponse)
	err := c.cc.Invoke(ctx, "/invoice.invoice.Msg/UpdateInvoice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteInvoice(ctx context.Context, in *MsgDeleteInvoice, opts ...grpc.CallOption) (*MsgDeleteInvoiceResponse, error) {
	out := new(MsgDeleteInvoiceResponse)
	err := c.cc.Invoke(ctx, "/invoice.invoice.Msg/DeleteInvoice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	Storeinvoice(context.Context, *MsgStoreinvoice) (*MsgStoreinvoiceResponse, error)
	CreateInvoice(context.Context, *MsgCreateInvoice) (*MsgCreateInvoiceResponse, error)
	UpdateInvoice(context.Context, *MsgUpdateInvoice) (*MsgUpdateInvoiceResponse, error)
	DeleteInvoice(context.Context, *MsgDeleteInvoice) (*MsgDeleteInvoiceResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (*UnimplementedMsgServer) Storeinvoice(ctx context.Context, req *MsgStoreinvoice) (*MsgStoreinvoiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Storeinvoice not implemented")
}
func (*UnimplementedMsgServer) CreateInvoice(ctx context.Context, req *MsgCreateInvoice) (*MsgCreateInvoiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateInvoice not implemented")
}
func (*UnimplementedMsgServer) UpdateInvoice(ctx context.Context, req *MsgUpdateInvoice) (*MsgUpdateInvoiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateInvoice not implemented")
}
func (*UnimplementedMsgServer) DeleteInvoice(ctx context.Context, req *MsgDeleteInvoice) (*MsgDeleteInvoiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteInvoice not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/invoice.invoice.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_Storeinvoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgStoreinvoice)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Storeinvoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/invoice.invoice.Msg/Storeinvoice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Storeinvoice(ctx, req.(*MsgStoreinvoice))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateInvoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateInvoice)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateInvoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/invoice.invoice.Msg/CreateInvoice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateInvoice(ctx, req.(*MsgCreateInvoice))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateInvoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateInvoice)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateInvoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/invoice.invoice.Msg/UpdateInvoice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateInvoice(ctx, req.(*MsgUpdateInvoice))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteInvoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteInvoice)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteInvoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/invoice.invoice.Msg/DeleteInvoice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteInvoice(ctx, req.(*MsgDeleteInvoice))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "invoice.invoice.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "Storeinvoice",
			Handler:    _Msg_Storeinvoice_Handler,
		},
		{
			MethodName: "CreateInvoice",
			Handler:    _Msg_CreateInvoice_Handler,
		},
		{
			MethodName: "UpdateInvoice",
			Handler:    _Msg_UpdateInvoice_Handler,
		},
		{
			MethodName: "DeleteInvoice",
			Handler:    _Msg_DeleteInvoice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "invoice/invoice/tx.proto",
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgStoreinvoice) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgStoreinvoice) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgStoreinvoice) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Due_Date) > 0 {
		i -= len(m.Due_Date)
		copy(dAtA[i:], m.Due_Date)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Due_Date)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Total_Amount) > 0 {
		i -= len(m.Total_Amount)
		copy(dAtA[i:], m.Total_Amount)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Total_Amount)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Invoice_Date) > 0 {
		i -= len(m.Invoice_Date)
		copy(dAtA[i:], m.Invoice_Date)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Invoice_Date)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Customer_Name) > 0 {
		i -= len(m.Customer_Name)
		copy(dAtA[i:], m.Customer_Name)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Customer_Name)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Invoice_Number) > 0 {
		i -= len(m.Invoice_Number)
		copy(dAtA[i:], m.Invoice_Number)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Invoice_Number)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgStoreinvoiceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgStoreinvoiceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgStoreinvoiceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCreateInvoice) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateInvoice) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateInvoice) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Due_Date) > 0 {
		i -= len(m.Due_Date)
		copy(dAtA[i:], m.Due_Date)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Due_Date)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Total_Amount) > 0 {
		i -= len(m.Total_Amount)
		copy(dAtA[i:], m.Total_Amount)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Total_Amount)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Invoice_Date) > 0 {
		i -= len(m.Invoice_Date)
		copy(dAtA[i:], m.Invoice_Date)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Invoice_Date)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Customer_Name) > 0 {
		i -= len(m.Customer_Name)
		copy(dAtA[i:], m.Customer_Name)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Customer_Name)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Invoice_Number) > 0 {
		i -= len(m.Invoice_Number)
		copy(dAtA[i:], m.Invoice_Number)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Invoice_Number)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateInvoiceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateInvoiceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateInvoiceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateInvoice) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateInvoice) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateInvoice) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Due_Date) > 0 {
		i -= len(m.Due_Date)
		copy(dAtA[i:], m.Due_Date)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Due_Date)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Total_Amount) > 0 {
		i -= len(m.Total_Amount)
		copy(dAtA[i:], m.Total_Amount)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Total_Amount)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Invoice_Date) > 0 {
		i -= len(m.Invoice_Date)
		copy(dAtA[i:], m.Invoice_Date)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Invoice_Date)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Customer_Name) > 0 {
		i -= len(m.Customer_Name)
		copy(dAtA[i:], m.Customer_Name)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Customer_Name)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Invoice_Number) > 0 {
		i -= len(m.Invoice_Number)
		copy(dAtA[i:], m.Invoice_Number)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Invoice_Number)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateInvoiceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateInvoiceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateInvoiceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgDeleteInvoice) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteInvoice) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteInvoice) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Due_Date) > 0 {
		i -= len(m.Due_Date)
		copy(dAtA[i:], m.Due_Date)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Due_Date)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Total_Amount) > 0 {
		i -= len(m.Total_Amount)
		copy(dAtA[i:], m.Total_Amount)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Total_Amount)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Invoice_Date) > 0 {
		i -= len(m.Invoice_Date)
		copy(dAtA[i:], m.Invoice_Date)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Invoice_Date)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Customer_Name) > 0 {
		i -= len(m.Customer_Name)
		copy(dAtA[i:], m.Customer_Name)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Customer_Name)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Invoice_Number) > 0 {
		i -= len(m.Invoice_Number)
		copy(dAtA[i:], m.Invoice_Number)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Invoice_Number)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDeleteInvoiceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteInvoiceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteInvoiceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgStoreinvoice) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Invoice_Number)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Customer_Name)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Invoice_Date)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Total_Amount)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Due_Date)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgStoreinvoiceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCreateInvoice) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Invoice_Number)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Customer_Name)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Invoice_Date)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Total_Amount)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Due_Date)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreateInvoiceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateInvoice) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Invoice_Number)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Customer_Name)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Invoice_Date)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Total_Amount)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Due_Date)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpdateInvoiceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgDeleteInvoice) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Invoice_Number)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Customer_Name)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Invoice_Date)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Total_Amount)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Due_Date)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgDeleteInvoiceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgStoreinvoice) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgStoreinvoice: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgStoreinvoice: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Invoice_Number", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Invoice_Number = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Customer_Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Customer_Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Invoice_Date", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Invoice_Date = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Total_Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Total_Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Due_Date", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Due_Date = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgStoreinvoiceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgStoreinvoiceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgStoreinvoiceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateInvoice) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateInvoice: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateInvoice: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Invoice_Number", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Invoice_Number = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Customer_Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Customer_Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Invoice_Date", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Invoice_Date = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Total_Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Total_Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Due_Date", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Due_Date = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateInvoiceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateInvoiceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateInvoiceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateInvoice) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateInvoice: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateInvoice: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Invoice_Number", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Invoice_Number = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Customer_Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Customer_Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Invoice_Date", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Invoice_Date = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Total_Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Total_Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Due_Date", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Due_Date = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateInvoiceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateInvoiceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateInvoiceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteInvoice) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteInvoice: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteInvoice: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Invoice_Number", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Invoice_Number = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Customer_Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Customer_Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Invoice_Date", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Invoice_Date = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Total_Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Total_Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Due_Date", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Due_Date = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteInvoiceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteInvoiceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteInvoiceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
